name: Java Format Check

on:
  pull_request:
    branches: [master]
    paths:
      - "watcher_service/**"
      - "validator_service/**"
      - ".github/workflows/format-check-java.yml"
  push:
    branches: [master]
    paths:
      - "watcher_service/**"
      - "validator_service/**"
      - ".github/workflows/format-check-java.yml"


jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "26"

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Make Gradle wrapper executable
        run: |
          chmod +x watcher_service/gradlew
          chmod +x validator_service/gradlew

      - name: Spotless format check (watcher)
        working-directory: watcher_service
        run: ./gradlew spotlessCheck

      - name: Spotless format check (validator)
        working-directory: validator_service
        run: ./gradlew spotlessCheck
