name: Java Tests

on:
  pull_request:
    branches: [master]
    paths:
      - "watcher_service/**"
      - "validator_service/**"
      - "parser_service/**"
      - ".github/workflows/tests-java.yml"
  push:
    branches: [master]
    paths:
      - "watcher_service/**"
      - "validator_service/**"
      - "parser_service/**"
      - ".github/workflows/tests-java.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "26"

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Make Gradle wrapper executable
        run: |
          chmod +x watcher_service/gradlew
          chmod +x validator_service/gradlew
          chmod +x parser_service/gradlew

      - name: Run watcher tests
        working-directory: watcher_service
        run: ./gradlew test

      - name: Run validator tests
        working-directory: validator_service
        run: ./gradlew test

      - name: Run parser tests
        working-directory: parser_service
        run: ./gradlew test
